[package]
name = "sentiric-rtp-core"
version = "1.1.0"  # <--- BUMP
edition = "2021"
description = "RTP packetization and Audio Codec (G.711/G.729) wrapper. Production Stable."
authors = ["Sentiric Team"]
license = "AGPL-3.0"

[dependencies]
# Runtime için sadece libc (C tipleri için)
libc = "0.2"

[build-dependencies]
# Derleme anında C kodlarını derlemek için
cc = "1.0"
glob = "0.3"